[package]
name = "rockpass"
version = "0.8.0"
authors = ["Óscar García Amor"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://gitlab.com/ogarcia/rockpass"
documentation = "https://gitlab.com/ogarcia/rockpass"
homepage = "https://gitlab.com/ogarcia/rockpass"
description = """
A small and ultrasecure LessPass database API server written in Rust.
"""
keywords = ["lesspass", "sqlite", "database", "api", "server"]
edition = "2018"
include = ["migrations/", "src/", "diesel.toml", "LICENSE", "README.md", "rockpass.toml.example"]

[dependencies]
base64 = "0.21.0"
bcrypt = "0.14.0"
chrono = { version = "0.4.23", features = ["serde"] }
diesel = { version = "1.4.8", default-features = false, features = ["sqlite", "chrono"] }
diesel_migrations = "1.4.0"
hmac = "0.12.1"
jwt = "0.16.0"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rocket_sync_db_pools = { version = "0.1.0-rc.2", default-features = false, features = ["diesel_sqlite_pool"] }
sha2 = "0.10.6"
uuid = { version = "1.3.0", default-features = false, features = ["v4"] }
